name: ntp
description: Fetch accurate time or current DateTime object from (NTP) Network Time Protocol server.
version: 2.0.0
homepage: https://github.com/knezzz/ntp

environment:
  sdk: '>=3.3.0 <4.0.0'
